.TH XARCHIVER "1" "January 2025" "xarchiver" "User Commands"
.SH NAME
xarchiver \- GTK+ front end for archive management
.SH SYNOPSIS
.B xarchiver
[\fIOPTION\fR] [\fIarchive\fR]
.SH DESCRIPTION
Xarchiver is a lightweight, desktop environment independent GTK+ front end for
handling 7z, a (libraries), apk, AppImage, arj, bzip, bzip2, bzip3, cab, cb7,
cbr, cbt, cbz, chm, compress, cpio, docx, epub, exe (self-extracting Windows
archives), fbz, gzip, iso, jar, jsonlz4, lha, lrzip, lz4, lzip, lzma, lzop,
mozlz4, odt, oxt, rar, rzip, snap, squashfs, tar, xpi, xz, zip, zpaq, zstd,
tar.bz, tar.bz2, tar.bz3, tar.gz, tar.lrz, tar.lz, tar.lz4, tar.lzma, tar.lzo,
tar.rz, tar.xz, tar.Z, tar.zst and (without their package managers) deb and
rpm files.
.br
It recognizes file types by their file signature (magic number), not by
their extension, and uses various (de)compressor/(un)archiver command
line programs at runtime. It allows to list, test and create archives, add
and copy files to them, extract, delete, cut and drag files from them, edit
files in them, and paste and drop files into them. Password protected 7z,
arj, lrzip, rar and zip archives are supported and will be recognized.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-add\fR
add to archive by asking which files and quit
.TP
\fB\-c\fR, \fB\-\-compress\fR=\fIfile1 ... fileN\fR
add the given files by asking the name of the archive and quit
.TP
\fB\-d\fR, \fB\-\-ensure-directory\fR
extract archive to a containing directory and quit
.TP
\fB\-e\fR, \fB\-\-extract\fR
extract archive by asking the extraction directory and quit
.TP
\fB\-m\fR, \fB\-\-multi\-extract\fR
extract multiple archives by asking the extraction directory and quit
.TP
\fB\-x\fR, \fB\-\-extract\-to\fR=\fIdestination\fR
extract archive to the destination directory and quit

.TP
\fB\-i\fR, \fB\-\-info\fR
show found command-line programs to be used and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show version and exit
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use

.TP
\fB\-?\fR, \fB\-h\fR, \fB\-\-help\fR
show help options
.TP
\fB\-\-help\-gtk\fR
show GTK+ options
.TP
\fB\-\-help\-all\fR
show all help options
.SH AUTHOR
Ingo Br\[:u]ckl, (Giuseppe Torelli until 2014)
.SH REPORTING BUGS
<https://github.com/ib/xarchiver/issues>
